import {expect,test} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const base=process.env.KIRCHHOFF_LIVE_BASE_URL;
test.skip(!base,'Richiede il vero server Kirchhoff locale.');

test('PDF multipagina, scelta locale e ritaglio conservano il file e la revisione nel quaderno',async({page,request})=>{
 const pdf=await request.post(`${base}/api/pdf`,{data:{netlist:'V1 a 0 12 volt\nR1 a 0 6 ohm\n? current R1'}});
 expect(pdf.ok()).toBeTruthy();const bytes=await pdf.body();
 const remote:string[]=[];
 await page.route('**/*',route=>{const url=new URL(route.request().url());if(url.protocol.startsWith('http')&&!['localhost','127.0.0.1'].includes(url.hostname)){remote.push(url.hostname);void route.abort();}else void route.continue();});
 await page.goto(base!);await page.getByRole('button',{name:/Il tuo circuito/}).click();
 await page.locator('input[type=file][accept*="image/png"]').setInputFiles({name:'lezione-sorgente.pdf',mimeType:'application/pdf',buffer:bytes});
 const picker=page.getByRole('region',{name:'Pagina e ritaglio della fonte'});
 await expect(page.getByRole('combobox',{name:'Regime del circuito'})).toBeDisabled();
 await expect(picker.getByRole('button',{name:'Usa pagina e ritaglio'})).toBeEnabled();
 await picker.getByRole('spinbutton',{name:'Pagina del PDF',exact:true}).fill('2');
 await expect(picker.getByRole('button',{name:'Usa pagina e ritaglio'})).toBeEnabled();
 await picker.getByRole('spinbutton',{name:'Larghezza ritaglio percentuale',exact:true}).fill('90');
 await picker.getByRole('spinbutton',{name:'Altezza ritaglio percentuale',exact:true}).fill('80');
 await picker.getByRole('button',{name:'Usa pagina e ritaglio'}).click();
 await expect(page.getByRole('combobox',{name:'Regime del circuito'})).toBeEnabled();
 await expect(page.getByText(/Fonte PDF: pagina 2 di/)).toBeVisible();
 await page.getByRole('button',{name:'Aggiungi generatore di tensione',exact:true}).click();
 await page.getByLabel('Valore V1',{exact:true}).fill('12');await page.getByLabel('Primo morsetto V1',{exact:true}).fill('a');await page.getByLabel('Secondo morsetto V1',{exact:true}).fill('0');
 await page.getByRole('button',{name:'Aggiungi resistore',exact:true}).click();
 await page.getByLabel('Valore R1',{exact:true}).fill('6');await page.getByLabel('Primo morsetto R1',{exact:true}).fill('a');await page.getByLabel('Secondo morsetto R1',{exact:true}).fill('0');
 await page.getByRole('combobox',{name:'Grandezza da trovare',exact:true}).selectOption('current');
 await page.getByRole('combobox',{name:'Componente della domanda',exact:true}).selectOption('R1');
 await page.getByRole('checkbox',{name:/Ho confrontato/}).check();await page.getByRole('button',{name:/Risolvi e spiega/}).click();
 await expect(page.getByRole('dialog')).toBeHidden();
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Salva quaderno ↓'}).click();
 const saved=JSON.parse(await readFile(await (await download).path(),'utf8'));
 expect(saved.sourceArtifact.kind).toBe('pdf');
 expect(saved.sourceArtifact.original.sha256).toBe(createHash('sha256').update(bytes).digest('hex'));
 expect(Buffer.from(saved.sourceArtifact.original.dataURL.split(',')[1],'base64')).toEqual(bytes);
 expect(saved.sourceArtifact.selection.page).toBe(2);expect(saved.sourceArtifact.selection.totalPages).toBeGreaterThanOrEqual(2);
 expect(saved.sourceArtifact.selection.crop).toEqual({x:0,y:0,width:.9,height:.8});
 expect(saved.sourceArtifact.prepared.sha256).toBe(saved.priorImageSha256);expect(remote).toEqual([]);
});
