import {expect,test} from '@playwright/test';
import {execFileSync} from 'node:child_process';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';

const base=process.env.KIRCHHOFF_LIVE_BASE_URL;
const root=resolve(process.cwd(),'..');
const directory=resolve(root,'../kirchhoff-ac-algebra-evidence-20261003/browser');
const sample='@ac 100 rad/s\n@amplitude rms\nV1 a 0 10 volt 30deg\nR1 a b 3 ohm\nL1 b c 1/25 henry\nC1 c 0 1/100 farad\n? power V1';
test.skip(!base,'Avvia il server Python reale e imposta KIRCHHOFF_LIVE_BASE_URL.');

for(const amplitude of ['rms','peak'])test(`Potenza AC ${amplitude}: rifiuto unspecified, S/P/Q, PDF e quaderno ricalcolato`,async({page},info)=>{
 const errors:string[]=[];
 page.on('pageerror',error=>errors.push(error.message));
 await page.goto(base!);
 await page.getByRole('button',{name:/Il tuo circuito/}).click();
 await page.getByRole('button',{name:'Componenti e collegamenti'}).click();
 if(!await page.getByRole('textbox',{name:'Circuito da risolvere'}).isVisible())await page.getByText('Vista esperta: testo del circuito',{exact:true}).click();
 await page.getByRole('textbox',{name:'Circuito da risolvere'}).fill(sample.replace('rms','unspecified'));
 await page.getByRole('button',{name:/Risolvi e spiega/}).click();
 await expect(page.getByRole('dialog').getByRole('alert')).toContainText('La potenza richiede');
 const netlist=sample.replace('rms',amplitude);
 if(!await page.getByRole('textbox',{name:'Circuito da risolvere'}).isVisible())await page.getByText('Vista esperta: testo del circuito',{exact:true}).click();
 await page.getByRole('textbox',{name:'Circuito da risolvere'}).fill(netlist);
 const solved=page.waitForResponse(response=>response.url().endsWith('/api/solve')&&response.request().method()==='POST');
 await page.getByRole('button',{name:/Risolvi e spiega/}).click();
 const lesson=await (await solved).json();
 expect(lesson.conventions.power_calculated).toBe(true);
 expect(lesson.verification.product_verified).toBe(false);
 await expect(page.getByRole('heading',{name:'Fissiamo regime, fase e riferimenti'})).toBeVisible();
 for(let index=0;index<64&&!await page.getByRole('heading',{name:'Dichiariamo la potenza e i segni'}).isVisible();index++)await page.getByRole('button',{name:'Passo successivo'}).click();
 await expect(page.getByRole('heading',{name:'Dichiariamo la potenza e i segni'})).toBeVisible();
 await expect(page.locator('.student-equations')).toContainText(amplitude==='peak'?'S = V * conj(I) / 2':'S = V * conj(I)');
 await page.getByRole('button',{name:'Passo successivo'}).click();
 await expect(page.locator('.student-equations')).toContainText('Somma P = 0 W');
 await expect(page.locator('.student-equations')).toContainText('Somma Q = 0 var');
 await page.getByRole('button',{name:'Passo successivo'}).click();
 const scalar=amplitude==='peak'?'-25/3':'-50/3';
 await expect(page.locator('.student-result')).toContainText('S =');
 await expect(page.locator('.student-result math')).toBeVisible();
 await expect(page.locator('.student-result math mfrac')).toHaveCount(2);
 await expect(page.locator('.student-equations math').nth(1).locator('mfrac mn').first()).toHaveText(amplitude==='peak'?'25':'50');
 await expect(page.locator('.student-equations math').nth(1).locator('mo').last()).toHaveText('−');
 await expect(page.locator('.student-equations math').nth(2).locator('mfrac mn').last()).toHaveText('3');
 await expect(page.locator('.student-equations math').nth(2)).toContainText('var');
 await page.getByText('Controllo del risultato e provenienza').click();
 await expect(page.getByText(/prodotto rettangolare indipendente/)).toBeVisible();
 await mkdir(directory,{recursive:true});
 const artifact=resolve(directory,`${amplitude}-${info.project.name}`);
 await writeFile(`${artifact}-lesson.json`,JSON.stringify(lesson,null,2)+'\n');
 const pdf=page.waitForEvent('download');
 await page.getByRole('button',{name:'Scarica PDF ↓'}).click();
 await (await pdf).saveAs(`${artifact}-lesson.pdf`);
 expect((await readFile(`${artifact}-lesson.pdf`)).subarray(0,4).toString()).toBe('%PDF');
 const notebook=page.waitForEvent('download');
 await page.getByRole('button',{name:'Salva quaderno ↓'}).click();
 const saved=await readFile(await (await notebook).path());
 expect(JSON.parse(saved.toString()).netlist).toBe(netlist);
 expect(JSON.parse(saved.toString()).answerExact).toBe(`(${scalar}) + j*(${scalar})`);
 await writeFile(`${artifact}-notebook.json`,saved);
 await page.reload();
 const recalculated=page.waitForResponse(response=>response.url().endsWith('/api/solve')&&response.request().method()==='POST');
 await page.locator('input[type=file][accept*="application/json"]').setInputFiles({name:'power.json',mimeType:'application/json',buffer:saved});
 expect((await (await recalculated).json()).answer).toEqual(lesson.answer);
 await expect(page.getByText(/Quaderno riaperto e soluzione ricalcolata/)).toBeVisible();
 await expect(page.locator('.student-result')).toContainText('S =');
 await expect(page.locator('.student-result math')).toBeVisible();
 await expect(page.locator('.student-result math mfrac')).toHaveCount(2);
 expect(await page.locator('body').evaluate(body=>body.scrollWidth<=window.innerWidth)).toBe(true);
 expect(errors).toEqual([]);
 await page.locator('.student-result').scrollIntoViewIfNeeded();
 await page.screenshot({path:`${artifact}.png`,fullPage:false});
});

test('MCP App potenza peak: SDK reale e host locale di prova',async({page},info)=>{
 const errors:string[]=[];
 page.on('pageerror',error=>errors.push(error.message));
 const python=resolve(root,'.venv/bin/python');
 const html=execFileSync(python,['-c','from kirchhoff.api.mcp_server import app_html; print(app_html())'],{cwd:root,encoding:'utf8'});
 await page.exposeFunction('callKirchhoffPower',async(params:{name:string;arguments?:unknown})=>{
  const code='import asyncio,json,sys\nfrom mcp import Client\nfrom kirchhoff.api.mcp_server import build_server\nasync def run():\n async with Client(build_server()) as client:\n  params=json.loads(sys.argv[1]); result=await client.call_tool(params["name"],params.get("arguments",{})); print(json.dumps(result.model_dump(by_alias=True,exclude_none=True)))\nasyncio.run(run())';
  return JSON.parse(execFileSync(python,['-c',code,JSON.stringify(params)],{cwd:root,encoding:'utf8'}));
 });
 await page.goto(base!);
 await page.setContent('<title>Potenza AC — host MCP locale di prova</title><iframe title="Kirchhoff MCP App" style="width:100%;height:1100px;border:0"></iframe>');
 await page.evaluate(({html})=>{
  const frame=document.querySelector('iframe')!;
  window.addEventListener('message',async(event)=>{
   if(event.source!==frame.contentWindow)return;
   const message=event.data;
   if(message?.jsonrpc!=='2.0'||message.id===undefined)return;
   let result;
   if(message.method==='ui/initialize')result={protocolVersion:message.params.protocolVersion,hostInfo:{name:'Host locale di prova',version:'1.0.0'},hostCapabilities:{serverTools:{}},hostContext:{theme:'light',displayMode:'inline'}};
   else if(message.method==='tools/call')result=await (window as unknown as {callKirchhoffPower:(params:unknown)=>Promise<unknown>}).callKirchhoffPower(message.params);
   else result={};
   frame.contentWindow!.postMessage({jsonrpc:'2.0',id:message.id,result},'*');
  });
  frame.srcdoc=html;
 },{html});
 const app=page.frameLocator('iframe');
 await expect(app.locator('#status')).toContainText('Host collegato');
 await app.getByRole('textbox',{name:'Circuito confermato e domanda'}).fill(sample.replace('rms','peak'));
 await app.getByRole('button',{name:'Verifica e spiega'}).click();
 await expect(app.locator('#status')).toContainText('prodotto rettangolare indipendente');
 for(let index=0;index<64&&await app.getByRole('button',{name:'Dopo →'}).isEnabled();index++)await app.getByRole('button',{name:'Dopo →'}).click();
 await expect(app.locator('#answer math mfrac')).toHaveCount(2);
 await expect(app.locator('#answer')).toContainText('S =');
 await expect(app.locator('#answer')).toContainText('VA');
 await expect(app.locator('#equations math').nth(1).locator('mfrac mn').first()).toHaveText('25');
 await expect(app.locator('#equations math').nth(2).locator('mfrac mn').last()).toHaveText('3');
 expect(errors).toEqual([]);
 await mkdir(directory,{recursive:true});
 await app.locator('#answer').scrollIntoViewIfNeeded();
 await page.screenshot({path:resolve(directory,`mcp-peak-${info.project.name}.png`),fullPage:false});
});
